# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v .
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: ./VaultwardenBackup
